### ISSUE TITLE
Error while requiring ftpd.

### ISSUE THREAD

**Issue by FarhanMS123** [nodeftpd/nodeftpd#139]
I tried to requiring ftpd via test.js and node console.
in test.js, it returns : 
```
H:\NodeJS\ftpd>node "./node_modules/ftpd/test.js"
util.js:961
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:961:11)
    at Object.<anonymous> (H:\NodeJS\ftpd\node_modules\ftpd\lib\ftpd.js:67:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (H:\NodeJS\ftpd\node_modules\ftpd\test.js:1:74)
```
and in node console. It returns : 
```
H:\NodeJS\ftpd>node
> var ftpd = require("ftpd");
TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:961:11)
    at Object.<anonymous> (H:\NodeJS\ftpd\node_modules\ftpd\lib\ftpd.js:67:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at repl:1:12
>
```
How, can I fixed it?

**Comment by FarhanMS123** [comment]
owh. fixed. I just need to add
```
process.EventEmitter = require("events");
//and everything gonna be okay
```
