### ISSUE TITLE
TLS secure socket pair missing ssl property

### ISSUE THREAD

**Issue by ghost** [nodeftpd/nodeftpd#148]
When using tls the framework failed because _ssl and ssl not defined:

(node:7) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.TLSSocket instead.
 /opt/nodeServer/node_modules/ftpd/lib/starttls.js:62
 var verifyError = (pair._ssl || pair.ssl).verifyError();
                                            ^

TypeError: Cannot read property 'verifyError' of undefined
   at SecurePair.<anonymous> (/opt/nodeServer/node_modules/ftpd/lib/starttls.js:62:47)
   at SecurePair.emit (events.js:315:20)
   at TLSSocket.<anonymous> (tls.js:313:46)
   at Object.onceWrapper (events.js:421:28)
   at TLSSocket.emit (events.js:315:20)
   at TLSSocket._finishInit (_tls_wrap.js:935:8)
   at TLSWrap.onhandshakedone (_tls_wrap.js:142:9)
   at DuplexSocket.ondata (internal/js_stream_socket.js:72:22)
   at DuplexSocket.emit (events.js:315:20)
   at addChunk (_stream_readable.js:297:12)
   at readableAddChunk (_stream_readable.js:273:9)
   at DuplexSocket.Readable.push (_stream_readable.js:214:10)
   at DuplexSocket._write (internal/streams/duplexpair.js:31:24)
   at doWrite (_stream_writable.js:392:12)
   at writeOrBuffer (_stream_writable.js:374:5)
   at DuplexSocket.Writable.write (_stream_writable.js:314:12)

When hardcoding verifyError to null everything works as expected. I am using self signed certs.

**Comment by mk-pmb** [comment]
Which versions are you using of nodeftpd. nodejs, OS, and which OS?

**Comment by johanneswilke** [comment]
Just tested it again in a plain project with Node v14.11.0, npm 6.14.6 and under MacOS 10.15.6 and everything worked. Sadly i don't have the code which failed anymore so i can't check it again there. Maybe a problem with other dependency's or so. You could think about changing it due to deprecation DEP0064 anyway but seems to work now.

**Comment by mk-pmb** [comment]
Thanks for testing it again!
